import { NameListBySlot } from "src/app/data/referenceTables/nameListBySlot";


export const namesListBySlot: NameListBySlot[] = [
    {
      "slotKey": "two-handed",
      "names": [
         "Arbalète",
         "Arc",
         "Arquebuse",
         "Baliste",
         "Bardiche",
         "Bâton",
         "Bombarde",
         "Chu-ko-nu",
         "Couleuvrine",
         "Faux",
         "Gastrophète",
         "Katana",
         "Lance",
         "Maul",
         "Mousquet",
         "Nodachi",
         "Shillelagh",
         "Trident",
         "Yari",
         "Zweihander"
      ]
   },
    {
      "slotKey": "main-weapon",
      "names": [
         "Bec-de-corbeau",
         "Chakram",
         "Cimeterre",
         "Epieu",
         "Fléau",
         "Francisque",
         "Glaive",
         "Hache",
         "Javelot",
         "Jitte",
         "Marteau",
         "Masse",
         "Morgenstern",
         "Pistolet",
         "Rapière",
         "Sabre",
         "Saignoir",
         "Shuriken",
         "Tromblon",
         "Tulwar"
      ]
   },
    {
      "slotKey": "secondary-weapon",
      "names": [
         "Aiguille",
         "Bouclier",
         "Broquel",
         "Casse-mâchoire",
         "Dague",
         "Ecu",
         "Egide",
         "Eventail",
         "Griffe",
         "Katar",
         "Kukri",
         "Pavois",
         "Rempart",
         "Rondache",
         "Sai",
         "Scutum",
         "Serpe",
         "Targe",
         "Umbo",
         "Wakizashi"
      ]
   },
    {
      "slotKey": "legs",
      "names": [
         "Bottes",
         "Bracelet de cheville",
         "Braies",
         "Brodequins",
         "Ceinture",
         "Ceinturon",
         "Chaîne d'orteil",
         "Chevillère",
         "Chausses",
         "Chaussettes",
         "Chaussures",
         "Collants",
         "Cuissards",
         "Grèves",
         "Guincheuses",
         "Jambières",
         "Haut-de-chausse",
         "Sandales",
         "Sangle",
         "Solerets"
      ]
   },
    {
      "slotKey": "arms",
      "names": [
         "Anneau",
         "Bague",
         "Bracelet",
         "Brassards",
         "Cestes",
         "Déflecteurs",
         "Cubitières",
         "Empoigneurs",
         "Gantelets",
         "Gants",
         "Garde-bras",
         "Garde-poignets",
         "Manchons",
         "Maniques",
         "Mitaines",
         "Poignes",
         "Poings",
         "Protège-bras",
         "Protège-mains",
         "Semainier"
      ]
   },
    {
      "slotKey": "head",
      "names": [
         "Armet",
         "Barbute",
         "Bassinet",
         "Bindi",
         "Capuchon",
         "Casque",
         "Capuche",
         "Cervellière",
         "Couronne",
         "Crâne",
         "Diadème",
         "Heaume",
         "Masque",
         "Mempo",
         "Monocle",
         "Morion",
         "Sallet",
         "Shako",
         "Tiare",
         "Visage"
      ]
   },
    {
      "slotKey": "torso",
      "names": [
         "Armure",
         "Brigandine",
         "Cape",
         "Carapace",
         "Corset",
         "Cotte",
         "Couvre-épaule",
         "Cuirasse",
         "Echarpe",
         "Epaulières",
         "Espauliers",
         "Haubert",
         "Maille",
         "Manteau",
         "Mantelet",
         "Plastron",
         "Pourpoint",
         "Toison",
         "Torc",
         "Tunique"
      ]
   }
];